auth-frontend/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  scope "/sign-in" do
    get  "/",     to: "sign_in#show", as: :sign_in
    post "/",     to: "sign_in#create"
    get  "/back", to: "sign_in#back", as: :sign_in_back
  end
end

auth-frontend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

auth-frontend/app/controllers/sign_in_controller.rb
class SignInController < ApplicationController
  def show
    result = SignIn::ShowInteractor.call!(params: params)
    redirect_to result.redirect_to and return if result.skip?

    @login_challenge_id = result.login_challenge_id
  rescue Interactor::Failure
    head :bad_request
  end

  def create
    result = SignIn::CreateInteractor.call!(params: params)
    redirect_to result.redirect_to
  rescue Interactor::Failure => e
    head :bad_request and return if e.context.hydra_api_error?
    head :internal_server_error and return if e.context.internal_api_error?

    @errors = e.context.errors
    @login_challenge_id = e.context.login_challenge_id
    render :show
  end

  def back
    result = SignIn::BackInteractor.call!(params: params)
    redirect_to result.redirect_to
  rescue Interactor::Failure
    head :bad_request
  end
end

auth-frontend/app/helpers/application_helper.rb
module ApplicationHelper
end

auth-frontend/app/views/layouts/application.html.erb
<% default_title = "ORY Stack Learning (Auth Frontend)" %>

<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? "#{yield(:title)} - #{default_title}" : default_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

auth-frontend/app/views/sign_in/show.html.erb
<% content_for :title, t("sign_in.show.title") %>

<%= form_with do |f| %>
<%= f.hidden_field :login_challenge_id, value: @login_challenge_id %>

<%= f.label :email, t("sign_in.show.fields.email.label") %>
<%= f.email_field :email, value: params[:email] %>
<% if (@error_items || {})[:email] %>
  <p><strong><%= sanitize(t("sign_in.show.fields.email.errors.#{@error_items[:email]}")) %></strong></p>
<% end %>

<%= f.label :password, t("sign_in.show.fields.password.label") %>
<%= f.password_field :password, value: params[:password] %>
<% if (@error_items || {})[:password] %>
  <p><strong><%= sanitize(t("sign_in.show.fields.password.errors.#{@error_items[:password]}")) %></strong></p>
<% end %>

<%= f.submit t("sign_in.show.fields.submit.label") %>
<% end %>

<p><%= sanitize(t("sign_in.show.back_link"), href: sign_in_back_path(login_challenge_id: @login_challenge_id)) %></p>